version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      - node-network

  node-app:
    build: ./node-app
    entrypoint: ['dockerize', '-wait', 'tcp://db:3306', '-timeout', '20s']
    command: ['node', 'server.js']
    volumes:
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - node-network
  nginx:
    build: ./nginx
    depends_on:
      - node-app
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
